### PR TITLE
Added Kubernetes Provider

### PR DESCRIPTION
**Pull request by shpwrck**
I believe a simple kubernetes provider should be the default.
It currently leverages the built in kubernetes service account.

### CODE REVIEW

**Comment by alexei-led** [comment]
@shpwrck it's possible to mount K8s secret as file or env variable directly. What problem/use-case does this PR address? Thank you

**Comment by shpwrck** [comment]
Hey alexei! 
I realize that this doesn't add much security/functionality, but for people who would like to try this without having access to gcp or aws I think it acts as a simple example. It's a UX enhancement more than anything. My goal ultimately is to extend this to provide decryption with a colocated secrets solution.

**Review by alexei-led — CHANGES_REQUESTED** [review]
@shpwrck probably, worth to explain this in README: why does this provider was created (as a reference implementation, and maybe useful in some use cases). And add a link to the standard K8s way for dealing with secrets.

**Comment by alexei-led** [comment]
and rebase master, please

**Pull request closed without merging**
